import React from "react";
import PropTypes from "prop-types";
import {
  Activity,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  BarChart3,
  BookOpen,
  Bot,
  Brain,
  BrainCircuit,
  Building2,
  Calendar,
  ChartNoAxesCombined,
  ChartPie,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleOff,
  Clock3,
  CloudOff,
  CloudUpload,
  Code2,
  Coins,
  Compass,
  Copy,
  Cpu,
  Database,
  Download,
  Droplets,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  Film,
  Filter,
  FlaskConical,
  FolderOpen,
  Gem,
  GitBranch,
  Globe,
  GripVertical,
  HardDrive,
  Hourglass,
  Image,
  Info,
  KeyRound,
  Languages,
  Layers,
  Link2,
  ListChecks,
  LoaderCircle,
  Lock,
  LockOpen,
  Menu,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Network,
  PanelLeft,
  PauseCircle,
  Pencil,
  Play,
  Plus,
  Power,
  PowerOff,
  Puzzle,
  ReceiptText,
  RefreshCw,
  Rocket,
  Route,
  Save,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Speaker,
  Square,
  Sun,
  Terminal,
  Timer,
  Trash2,
  TriangleAlert,
  Upload,
  Users,
  Wifi,
  WifiOff,
  Workflow,
  X,
  Zap,
} from "lucide-react";

const ICON_MAP = {
  account_circle: Users,
  account_tree: GitBranch,
  add: Plus,
  air: Activity,
  api: Workflow,
  api_key: KeyRound,
  apikey: KeyRound,
  apps: Layers,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  attach_file: Link2,
  auto_awesome: Sparkles,
  auto_delete: Trash2,
  bar_chart: BarChart3,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "chart-pie": ChartPie,
  chart_no_axes_combined: ChartNoAxesCombined,
  chart_pie: ChartPie,
  block: Ban,
  blur_on: Sparkles,
  bolt: Zap,
  brush: Pencil,
  business: Building2,
  cached: RefreshCw,
  calendar_today: Calendar,
  cancel: CircleOff,
  chat: MessageSquare,
  check: Check,
  check_box: CheckSquare,
  check_box_outline_blank: Square,
  check_circle: CircleCheck,
  checklist: ListChecks,
  close: X,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  clean: Sparkles,
  cleaning_services: Sparkles,
  cloud: Workflow,
  cloud_off: CloudOff,
  cloud_queue: Workflow,
  cloud_sync: RefreshCw,
  cloud_upload: CloudUpload,
  code: Code2,
  computer: Monitor,
  content_copy: Copy,
  contrast: CircleOff,
  dark: Moon,
  dark_mode: Moon,
  dashboard: BarChart3,
  data_array: Database,
  data_object: Database,
  data_usage: BarChart3,
  database: Database,
  delete: Trash2,
  delete_forever: Trash2,
  delete_sweep: Trash2,
  developer_board: Cpu,
  diamond: Gem,
  dns: Network,
  download: Download,
  drag_indicator: GripVertical,
  edit: Pencil,
  edit_note: Pencil,
  Enter: ArrowRight,
  error: CircleAlert,
  expand_more: ChevronDown,
  extension: Puzzle,
  face: Users,
  file_upload: Upload,
  filter_alt: Filter,
  folder_open: FolderOpen,
  free: Sparkles,
  group: Users,
  group_work: Users,
  healthy: CircleCheck,
  health_and_safety: ShieldCheck,
  help: CircleHelp,
  hourglass_top: Hourglass,
  hub: Workflow,
  image: Image,
  image_search: Search,
  info: Info,
  input: ArrowDownToLine,
  key: KeyRound,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  lan: Network,
  language: Globe,
  layers: Layers,
  left_panel_close: PanelLeft,
  left_panel_open: PanelLeft,
  light: Sun,
  light_mode: Sun,
  link: Link2,
  local_fire_department: TriangleAlert,
  lock: Lock,
  lock_open: LockOpen,
  logout: ArrowRight,
  manage_accounts: Users,
  manage_search: Search,
  memory: BrainCircuit,
  memory_alt: Brain,
  menu: Menu,
  menu_book: BookOpen,
  mic: Mic,
  monitor_heart: Activity,
  monitoring: Activity,
  more_horiz: Ellipsis,
  movie: Film,
  music_note: Speaker,
  network_check: Network,
  oauth: ShieldCheck,
  ok: CircleCheck,
  open_in_new: ExternalLink,
  output: ArrowUp,
  pause_circle: PauseCircle,
  payments: Coins,
  perm_media: Image,
  play_arrow: Play,
  play_circle: Play,
  power_off: PowerOff,
  power_settings_new: Power,
  progress_activity: LoaderCircle,
  psychology: BrainCircuit,
  psychology_alt: Brain,
  public: Globe,
  receipt_long: ReceiptText,
  record_voice_over: Mic,
  refresh: RefreshCw,
  restart_alt: RefreshCw,
  rocket_launch: Rocket,
  route: Route,
  router: Route,
  save: Save,
  saved_search: Search,
  schedule: Clock3,
  science: FlaskConical,
  search: Search,
  search_off: SearchX,
  send: Send,
  settings: Settings,
  shield: Shield,
  shield_with_heart: ShieldCheck,
  smart_toy: Bot,
  spatial_audio: Speaker,
  speaker: Speaker,
  speed: Activity,
  stop: Square,
  storage: HardDrive,
  sync: RefreshCw,
  terminal: Terminal,
  timer: Timer,
  token: Coins,
  translate: Languages,
  travel_explore: Compass,
  ts_url: Link2,
  tune: SlidersHorizontal,
  tunnel_url: Link2,
  unfold_less: ChevronUp,
  upload: Upload,
  verified: CircleCheck,
  vertical_align_bottom: ArrowDownToLine,
  visibility: Eye,
  visibility_off: EyeOff,
  vpn_key: KeyRound,
  vpn_lock: ShieldCheck,
  warning: TriangleAlert,
  water_drop: Droplets,
  wifi: Wifi,
  wifi_off: WifiOff,
  wifi_tethering: Wifi,
};

export default function LucideIcon({
  name,
  className = "",
  size = undefined,
  strokeWidth = 2,
  absoluteStrokeWidth = false,
  ...props
}) {
  const Icon = ICON_MAP[name] || CircleHelp;

  return (
    <Icon
      className={className}
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      {...props}
    />
  );
}

LucideIcon.propTypes = {
  absoluteStrokeWidth: PropTypes.bool,
  className: PropTypes.string,
  name: PropTypes.string.isRequired,
  size: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  strokeWidth: PropTypes.number,
};
