services:
  pod:
    image: lazuardytech/pod
    container_name: pod
    restart: unless-stopped
    env_file: ../.env
    environment:
      SEARXNG_BASE_URL: http://searxng:8080/search
      REDIS_URL: redis://redis:6379
    ports:
      - "20128:20128"
    depends_on:
      - searxng
      - redis
    volumes:
      - pod-data:/app/data

  redis:
    image: redis:7-alpine
    container_name: pod-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  searxng:
    image: searxng/searxng:latest
    container_name: pod-searxng
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      BASE_URL: http://localhost:8888/
      BIND_ADDRESS: 0.0.0.0:8080
      INSTANCE_NAME: pod-searxng
    volumes:
      - searxng-config:/etc/searxng

volumes:
  pod-data:
  redis-data:
  searxng-config:
