import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "open-sse");
const generatedHeader = "// Generated by scripts/gen-open-sse-js-shims.ts; do not edit.";
const defaultExportPattern = /\bexport\s+default\b|export\s*\{[^}]*\bdefault\b[^}]*\}/m;

async function collectTsFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === "test") continue;
      files.push(...(await collectTsFiles(path)));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith(".ts") && !entry.name.endsWith(".d.ts")) {
      files.push(path);
    }
  }

  return files;
}

function createShim(source: string, tsFile: string): string {
  const tsBasename = basename(tsFile);
  const lines = [generatedHeader, `export * from "./${tsBasename}";`];

  if (defaultExportPattern.test(source)) {
    lines.push(`export { default } from "./${tsBasename}";`);
  }

  return `${lines.join("\n")}\n`;
}

const tsFiles = await collectTsFiles(root);

for (const tsFile of tsFiles) {
  const source = await readFile(tsFile, "utf8");
  const shimFile = tsFile.replace(/\.ts$/, ".js");
  await mkdir(dirname(shimFile), { recursive: true });
  await writeFile(shimFile, createShim(source, tsFile));
}

console.log(`Generated ${tsFiles.length} open-sse JS shims in ${relative(process.cwd(), root)}`);
